quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=Teeddy
quarkus.datasource.password=9098
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/crud_quarkus

# Hibernate Configuration
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
# HTTP Configuration
quarkus.http.port=8080